//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignedRequests
    {
        public int AssignmentID { get; set; }
        public Nullable<int> RequestID { get; set; }
        public Nullable<int> VolunteerID { get; set; }
    
        public virtual Requests Requests { get; set; }
        public virtual Volunteers Volunteers { get; set; }
    }
}
