//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.AssignedRequests = new HashSet<AssignedRequests>();
        }
    
        public int RequestID { get; set; }
        public Nullable<int> SeekerID { get; set; }
        public string RequestContent { get; set; }
        public string Status { get; set; }
        public DateTime Date { get; set; }
        public Nullable<int> ServiceID { get; set; }
        public Nullable<int> Hours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssignedRequests> AssignedRequests { get; set; }
        public virtual HelpSeekers HelpSeekers { get; set; }
        public virtual Services Services { get; set; }
    }
}
